"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:color_peach fg:surface0)\
$directory\
[](fg:color_peach bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_sapphire)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_sapphire bg:color_blue)\
$docker_context\
$conda\
[](fg:color_blue bg:color_pink)\
$time\
[ ](fg:color_pink)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
color_fg0 = '#cdd6f4'
color_fg1 = '#1e1e2e'
color_pink = '#f5c2e7'
color_blue = '#89b4fa'
color_sapphire = '#74c7ec'
color_green = '#a6e3a1'
color_teal = '#94e2d5'
surface0 = '#313244'
color_purple = '#cba6f7'
color_red = '#cc241d'
color_peach = '#fab387'

[os]
disabled = false
style = "bg:surface0 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:color_fg0"
style_root = "fg:color_fg0 bg:surface0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_fg1 bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_fg1 bg:color_green)]($style)'

[nodejs]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[c]
symbol = " "
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[rust]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[golang]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[php]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[java]
symbol = " "
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[kotlin]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[haskell]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[python]
symbol = ""
style = "bg:color_sapphire"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_sapphire)]($style)'

[docker_context]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $context) ](fg:color_fg1 bg:color_blue)]($style)'

[conda]
style = "bg:color_blue"
format = '[[ $symbol( $environment) ](fg:color_fg1 bg:color_blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_pink"
format = '[[  $time ](fg:color_fg1 bg:color_pink)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_teal)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_teal)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_peach)'
