#!/bin/bash

echo "Installing packages on macOS..."
brew install starship || { echo "Error installing starship"; exit 1; }
brew install zsh || { echo "Error installing zsh"; exit 1; }
brew install ripgrep || { echo "Error installing ripgrep"; exit 1; }
brew install lazygit || { echo "Error installing lazygit"; exit 1; }
brew install tmux || { echo "Error installing tmux"; exit 1; }
brew install neovim || { echo "Error installing neovim"; exit 1; }
brew install zoxide || { echo "Error installing zoxide"; exit 1; }
brew install fzf || { echo "Error installing fzf"; exit 1; }
