#!/bin/bash

# Check the operating system and install packages accordingly
if [[ "$OSTYPE" == "darwin"* ]]; then
  ./install_packages_macos
elif [[ $(grep -E "^(ID|NAME)=" /etc/os-release | grep -Eq "ubuntu|fedora")$? == 0 ]]; then
  ./install_packages_ubuntu_fedora
else
  echo "Unsupported operating system"
  exit 1
fi

# Change the default shell to zsh
./change_default_shell_to_zsh
